spring:
  application:
    name: lab1-app
  datasource:
    url: "${SPRING_DATASOURCE_URL}" #"jdbc:postgresql://localhost:5432/lab1_db"
    driverClassName: org.postgresql.Driver
    username: "${SPRING_DATASOURCE_USERNAME}" #lab1_user
    password: "${SPRING_DATASOURCE_PASSWORD}" #1
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
server:
  error:
    include-message: always
    include-binding-errors: always

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855