server:
  port: 8080

spring:
  cloud:
    gateway:
#      routes:
#        - id: security-service
#          uri: lb://security
#          predicates:
#            - Path=/security/**,/api-docs/**
#          filters:
#            - RewritePath=/security(?<segment>/?.*), $\{segment}
#            - TokenPreFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

